# Copyright (C) 2015-2017, NVIDIA CORPORATION. All rights reserved.
# Copyright (C) 2019, Nicholas Hubbard and contributors.

os: linux
dist: bionic
sudo: required
language: python
python: 3.6

env:
    global:
        - PROTOBUF_ROOT=~/protobuf
        - secure: "WSqrE+PQm76DdoRLRGKTK6fRWfXZjIb0BWCZm3IgHgFO7OE6fcK2tBnpDNNw4XQjmo27FFWlEhxN32g18P84n5PvErHaH65IuS9Nv6FkLlPXZlVqGNxbPmEA4oTkD/6Y6kZyZWZtLh2+/1ijuzQAPnIy/4BEuL8pdO+PsoJ9hYM="
    matrix:
        - DIGITS_TEST_FRAMEWORK=tensorflow WITH_PLUGINS=false
        - DIGITS_TEST_FRAMEWORK=none

cache:
    apt: true

install:
    - mkdir -p ~/.config/matplotlib
    - echo "backend:agg" > ~/.config/matplotlib/matplotlibrc
    - ./scripts/travis/install-protobuf.sh $PROTOBUF_ROOT
    - pip install tornado==4.5.3
    - pip install -r ./requirements.txt --force-reinstall
    - pip install -r ./requirements_test.txt
    - pip install -e .

script:
    - ./digits-test -v
