# Copyright (C) 2015-2017, NVIDIA CORPORATION. All rights reserved.
# Copyright (C) 2019, Nicholas Hubbard and contributors.

os: linux
dist: bionic
language: python
python: 3.6

env:
    global:
        - PROTOBUF_ROOT=~/protobuf
        - secure: "WSqrE+PQm76DdoRLRGKTK6fRWfXZjIb0BWCZm3IgHgFO7OE6fcK2tBnpDNNw4XQjmo27FFWlEhxN32g18P84n5PvErHaH65IuS9Nv6FkLlPXZlVqGNxbPmEA4oTkD/6Y6kZyZWZtLh2+/1ijuzQAPnIy/4BEuL8pdO+PsoJ9hYM="
    matrix:
        - DIGITS_TEST_FRAMEWORK=tensorflow WITH_PLUGINS=false
        - DIGITS_TEST_FRAMEWORK=none

addons:
    apt:
        packages:
            - protobuf-compiler
            - libprotoc-dev
            - caffe-cpu

cache: pip

install:
    - mkdir -p ~/.config/matplotlib
    - echo "backend:agg" > ~/.config/matplotlib/matplotlibrc
    - pip install tornado==6.0.3
    - pip install -r requirements.txt
    - pip install -e .

script:
    - ./digits-test
