#!/usr/bin/env bash
# Copyright (c) 2014-2017, NVIDIA CORPORATION.  All rights reserved.
# Copyright (C) 2019, Nicholas Hubbard and contributors.

set -e
DIGITS_MODE_TEST=1 python -m nose2 --no-path-adjustment "$@"
